baseURL = "https://jongnesia.or.id/"
title = "Jongnesia"
theme = "jongtheme"
paginate = 6

[params]
quote = "KAMI BANGGA MENJADI WARGA NEGARA REPUBLIK INDONESIA"
about = "Jongnesia merupakan organisasi yang ada di internet sebagai forum diskusi penggiat teknologi, di mana Anda dapat berdiskusi dan berbagi pengalaman, Namun bukan hanya diskusi terkait teknologi akan tetapi diskusi berbagai hal yang menjadi isu. Filosofi Jongnesia didasarkan pada makna kata &#39;JONG&#39; yang berasal dari Bahasa Belanda, yang berarti pemuda, sementara &#39;NESIA&#39; merujuk kepada Indonesia. Dengan demikian, Jongnesia dapat diartikan sebagai pemuda Indonesia."
footer = "Develop By JongNesia ♥"
description = "Pemuda Indonesia Berkarya , tempat sharing mengenai koding"
favicon= "static/favicon.png"

[[params.link]]
name = "Whatsapp"
url = ""
[[params.link]]
name = "Telegram"
url = "https://t.me/@jongnesia"
[[params.link]]
name = "Github"
url = "https://github.com/rysnant0-nes"



[[menus.main]]
name = "Home"
url = "/"
weight = 1

[[menus.main]]
name = "post"
url = "/post"
weight = 2

[[menus.main]]
name = "Koding"
url = "/koding"
weight = 3

[[menus.main]]
name = "Login"
url = "/admin"
weight = 3



[taxonomies]
  html = "html"
  css = "css"
  js = "js"



